### ISSUE TITLE
RubyからMySQLへ接続を確認する

### ISSUE THREAD

**Issue by keishimizu26629** [team1-apprentice-4th/Tmatter#28]

**Comment by ryumasann** [comment]
![image](https://github.com/team1-apprentice-4th/Tmatter/assets/42900957/f4281a6b-abb4-465d-a0bd-f5bc0f0e80f8)
修正後のものをdocker compose upしたところ上記エラー発生いたしました。
8行目でロードするdatabase用のyamlファイルがないのでエラーが発生しているようですが、修正中でしょうか？
![image](https://github.com/team1-apprentice-4th/Tmatter/assets/42900957/9a865761-4e90-4613-bf6f-0a0611303a3c)
![image](https://github.com/team1-apprentice-4th/Tmatter/assets/42900957/abe2824e-e72f-4682-bb30-f971d5383fef)

**Comment by keishimizu26629** [comment]
@ryumasann 
config/database.ymlファイルが消えてしまってますね、、
毎度なんでだろ？？再度ファイル作成して実行確認していただけますか？？

**Comment by ryumasann** [comment]
READMEに説明を追加してクローズ
